server:
  port: 8103

## Postgres
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://administrador.postgres.database.azure.com:5432/postgres?user=administrador&password=Badeggs13#&sslmode=require
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

